# Generated by Django 6.1 on 2026-09-05 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('fuente', models.CharField(choices=[('youtube', 'YouTube'), ('archivo', 'Archivo')], default='archivo', max_length=20)),
                ('referencia', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='Fragmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.TextField(blank=True)),
                ('inicio_s', models.FloatField()),
                ('fin_s', models.FloatField()),
                ('separar', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Obteniendo el recorte'), ('preparado', 'Listo para escuchar'), ('procesando', 'Analizando'), ('listo', 'Listo'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('paso', models.CharField(blank=True, max_length=120)),
                ('mensaje', models.TextField(blank=True)),
                ('avisos', models.JSONField(blank=True, default=list)),
                ('analisis', models.JSONField(blank=True, default=dict)),
                ('archivos', models.JSONField(blank=True, default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragmentos', to='transcripciones.cancion')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.PositiveIntegerField()),
                ('orden', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=5)),
                ('midi', models.PositiveSmallIntegerField()),
                ('inicio_s', models.FloatField()),
                ('duracion_s', models.FloatField()),
                ('confianza', models.FloatField()),
                ('cents', models.IntegerField()),
                ('fragmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='transcripciones.fragmento')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
