# Generated by Django 6.1 on 2026-09-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='audio_escucha',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cancion',
            name='audio_original',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cancion',
            name='duracion_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando el audio'), ('lista', 'Lista'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='cancion',
            name='mensaje',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cancion',
            name='origen',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cancion',
            name='paso',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cancion',
            name='separar',
            field=models.BooleanField(default=True),
        ),
    ]
